name: Mirror Repository
on:
  push:
    branches: [ master ]
jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      MIRROR_REPOSITORY: git@github.com:shinnosuke-ooyama/actions-test-mirror.git
      GIT_NAME: Shinnosuke Ooyama
      GIT_EMAIL: shinnosuke_oyama@citycom.co.jp
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'master'
    - name: add private key
      run: |
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: git config
      run: |
        git config user.name $GIT_NAME
        git config user.email $GIT_EMAIL
    - name: mirror
      run: |
        git remote add mirror $MIRROR_REPOSITORY
        git checkout master
        git push -u mirror master
