# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mirror:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      MIRROR_REPOSITORY: git@github.com:shinnosuke-ooyama/actions-test-mirror.git
      GIT_NAME: Shinnosuke Ooyama
      GIT_EMAIL: shinnosuke_oyama@citycom.co.jp
    steps:
    - uses: actions/checkout@v2
    - name: add private key
      run: |
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: git config
      run: |
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_MAILADDRESS
    - name: mirror
      run: |
        git push --mirror $MIRROR_REPOSITORY
